export default class FoldButtonEnum {
    static VERTICAL_START_LEFT = 'VERTICAL_START_LEFT';
    static VERTICAL_START_RIGHT = 'VERTICAL_START_RIGHT';
    static VERTICAL_MIDDLE_LEFT = 'VERTICAL_MIDDLE_LEFT';
    static VERTICAL_MIDDLE_RIGHT = 'VERTICAL_MIDDLE_RIGHT';
    static VERTICAL_END_LEFT = 'VERTICAL_END_LEFT';
    static VERTICAL_END_RIGHT = 'VERTICAL_END_RIGHT';

    static HORIZONTAL_START_DOWN = 'HORIZONTAL_START_TOP';
    static HORIZONTAL_START_UP = 'HORIZONTAL_START_BOTTOM';
    static HORIZONTAL_MIDDLE_DOWN = 'HORIZONTAL_MIDDLE_TOP';
    static HORIZONTAL_MIDDLE_UP = 'HORIZONTAL_MIDDLE_BOTTOM';
    static HORIZONTAL_END_DOWN = 'HORIZONTAL_END_TOP';
    static HORIZONTAL_END_UP = 'HORIZONTAL_END_BOTTOM';

    static DIAG_POS_START_LEFT = 'DIAG_POS_START_LEFT';
    static DIAG_POS_START_RIGHT = 'DIAG_POS_START_RIGHT';
    static DIAG_POS_MIDDLE_LEFT = 'DIAG_POS_MIDDLE_LEFT';
    static DIAG_POS_MIDDLE_RIGHT = 'DIAG_POS_MIDDLE_RIGHT';
    static DIAG_POS_END_LEFT = 'DIAG_POS_END_LEFT';
    static DIAG_POS_END_RIGHT = 'DIAG_POS_END_RIGHT';

    static DIAG_NEG_START_LEFT = 'DIAG_NEG_START_LEFT';
    static DIAG_NEG_START_RIGHT = 'DIAG_NEG_START_RIGHT';
    static DIAG_NEG_MIDDLE_LEFT = 'DIAG_NEG_MIDDLE_LEFT';
    static DIAG_NEG_MIDDLE_RIGHT = 'DIAG_NEG_MIDDLE_RIGHT';
    static DIAG_NEG_END_LEFT = 'DIAG_NEG_END_LEFT';
    static DIAG_NEG_END_RIGHT = 'DIAG_NEG_END_RIGHT';
}